window.npcFlavor = {
	name: 'Flavor',
	items: [
		'Smells of pickles',
		'Pimple on nose',
		'Acne',
		'Bright yellow scarf',
		'Missing all but one tooth',
		'Missing front teeth',
		'Terribly bad breath',
		'Very clean',
		'Tattooed',
		'Muscular',
		'Thin',
		'Tall',
		'Short',
		'Fidgets',
		'Smokes a pipe',
		'Loves reading',
		'Missing finger',
		'Extravagent clothing',
		'Falls asleep easily',
		'Lots of jewelery',
		'Covered in dirt',
		'Always sketching',
		'Gambling addict',
		'Attractive',
		'Ugly',
		'Smells of fresh cut grass',
		'Always itchy',
		'Nervous - always looking over shoulder',
		'Jogs in place while talking',
		'Always snacking, talks with their mouth open',
		'Carries a notebook and writes everything down - whether it seems important or not',
		'talks to themselves',
		'Announces his/her emotions before speaking, but speaks monotonously. "Enthusiastic. I love the color of your sweater."',
		'Puffing a cigar, but coughing as if s/he doesn\'t smoke often.',
		'Carries a small pet around and speaks for it.',
		'Terrified of magic. Distances themselves from spellcasters and flinches at anything from fireball to prestidigitation.',
		'Uses air quotes wrong, meaning to add "emphasis" instead (for instance, I\'m so "pleased" to see you; There\'s a great "reward" in it for you; You\'re a "great" DM.)',
		'It\'s as though blinking doesn\'t come naturally to them, always scrunching up their face to do so',
		'Often belches loudly and is overly apologetic for doing so',
		'Is constantly slicking back their hair nervously',
		'Always trying to feed people ("You look hungry.", "You\'re too skinny! Eat this!", etc.).',
		'Always impeccably dressed: hat, coat, and a co-ordinated handkerchief in a jacket pocket. They have a hanky for themselves in a back pocket.',
		'Has a "lazy" eye. Except it\'s actually looking at the other party members or one of the doors.',
		'Is blind. But has crazy high perception so they just can\'t read facial expressions.',
		'Very obviously picks wedgies and sniffs fingers afterwards',
		'Random pronounced eye twitch, which NPC will tell you he had ever since he won a fight with an owl bear',
		'Appears to be glaring angrily at whoever talks to them. Is not actually ever really angry.',
		'They are wearing a different, ridiculous hat whenever the PCs see them',
		'They do not speak common, but speak almost any other language.',
		'Looks so ordinary that you can\'t find a single distinctive thing about them. Perfectly average',
		'Ears stick out a lot',
		'Has buck teeth',
		'Has an unnusually pointy nose',
		'Has an unnusually flat nose',
		'Has long, stright hair',
		'Has long, wavy hair',
		'Has long, curly hair',
		'Hair is in matted dreadlocks - which smell foul',
		'Has short hair',
		'Has a distinctive monobrow',
		'Is blind in one eye',
		'Has a scar over their left eye',
		'The tip of their nose has been cut off',
		'Smells faintly of dog shit',
		'Smells like a wet dog',
		'Wears a wig. Flip a coin to determine if it\'s a good or a bad wig',
		'Plays with a ring on his finger',
		'Multi-names. This NPC seems to give a different name each time when asked. Maybe he/she doesn\'t even know his/her own true name.',
		'Brandy addict. This NPC is always looking for a bottle of his/her favorite rare brandy, but settles for the cheap kind too.',
		'Pants on fire. This NPC lies all the time, even though it\'s pretty clear they are lies and even if the PCs point out the NPC is telling lies, he/she just keeps on lying.',
		'Kinky past. This NPC has a bite wound on his/her cheek that looks suspiciously like the bite of a human.',
		'Milkstache. This NPC has a clear fondness for milk, visible by the almost permanent milkstache on his/her upper lips.',
		'Pockmarks. This NPC has his/her face covered in the permanent impression that the pocks left.',
		'Armpit eater. This NPC often sniffs his armpits, then proceeds to pick something out of it and eat it.',
		'Wears a fake beard',
		'Beautiful. This NPC is incredibly beautiful, and the party will need to do a DC 10 charisma save to not be completely flustered by this NPCs beauty.',
		'Ugly. The party needs to do a constitution saving throw of DC 10, or they\'ll puke.',
		'Is cross eyed',
		'Has one wooden leg, just like the classic pirate captains used to have.',
		'Missing eyebrows. This NPC has no eyebrows. It\'s really difficult to see what kind of expression he or she is making, therefore players have disadvantage on wisdom (Insight) checks concerning this NPC.',
		'This NPC is constantly talking about the end of the world, which, according to him/her, is just around the corner. Hide yo wife, hide yo kids!',
		'Seemingly Disturbed. This NPC looks very disturbed. He/She shakes all the time, constantly watches his/her surroundings and jumps in the air in fright from every little noise.',
		'Not a care in the world. This NPC is unbelievably happy. They only see the good in life and are extremely positive.',
		'Classic Tammy. This NPC has underwear visible above his or her pants. It\'s not that his/her pants are really low, but his/her underwear is just really high. Roll a d4 to determine the state of the underwear, 1: Clean, nothing special, 2: Dirty and torn, 3: Obviously way too tight, 4: Very sexy.',
		'Weirdest Mutton Chops Ever. This NPC, whether it\'s a he or a she doesn\'t matter, has the weirdest mutton chops anyone has ever seen. They are a different color than the rest of his/her hair and they are somehow intricately braided.',
		'Shaving Sucks. This NPC is very bad at shaving. If it\'s a man, he has a lot of small cuts on his face. With a successful DC8 perception or insight check it\'s pretty clear that they are the result of terrible shaving. If the NPC is a woman, it is almost the same, but instead the cuts are located on her legs',
		'Wild Accuser. This NPC accuses everyone he talks to of minor crimes, like littering, or making too much noise.',
		'Bless you! This NPC has a permanent cold. Always a runny nose and sneezing all the time.',
		'Broken down. This NPC has a broken limb. Roll a d4 to decide which: 1: Their good arm, 2: Their other arm, 3: One leg, 4: Both legs and their good arm.',
		'Permanent Ink. This NPC has a large tattoo of an animal\'s head on their neck. If you can\'t think of an animal yourself then it\'s a chicken\'s head.',
		'Smells of lavender and expensive oils',
		'Squinter. This NPC squints their eyes at the party. It looks like he/she needs a pair of glasses.',
		'Want a cookie? This NPC bakes their own cookies and offers to anyone and everyone to try. Roll 1d6/2 to determine the quality. 1: Terrible, bitter and is that a hair? 2: Average, OK cookies. 3: These are amazing, crunchy, sweet and something you can\'t quite put your finger on but it\'s awesome.',
		'Tattoo of someone\'s name on their neck',
		'Has arcane symbols tattooed on their arms - a faded reminder of a more wild youth',
		
	]
}