window.npcProfessions = {
	name: 'Professions',
	items: [
        'Alchemist',
        'Apothecary',
        'Architect',
        'Artist',
        'Astrologer',
        'Beggar',
        'Bounty Hunter',
		'Baker',
        'Barber',
        'Bartender',
        'Blacksmith',
        'Brewer',
        'Butcher',
        'Carpenter',
        'Cobbler',
        'Cook',
        'Farmer',
        'Fisherman',
        'Gardener',
        'Glassblower',
        'Hunter',
        'Jeweler',
        'Leatherworker',
        'Mason',
        'Miller',
        'Miner',
        'Painter',
        'Potter',
        'Sailor',
        'Shepherd',
        'Soldier',
        'Tailor',
        'Tanner',
        'Tavernkeeper',
        'Thatcher',
        'Weaver',
        'Woodcarver',
        'Woodcutter',
	]
};