window.punchlines = {
	name: 'Punchlines',
	items: [
		'so I says to the guy-I says "that\'s not your nephew! That\'s a flail snail with a mace infection!"',
		'and that\'s when I said "beholder? I hardly know her!"',
		'so then I told her "madam it couldn\'t have been my dog, he was eaten by an aboleth yesterday!"',
		'So then I looked this beholder right in the eye, and I -"which one?" Piped the old codger in the corner of the room',
		'and there it was. The most magnificent mermaid I\'ve ever seen. And as I move in for a passionate kiss, I wake up. It was only a wet dream.',
		'And that\'s the second time I got giant crabs',
		'So I says "that\'s no displacer beast, that\'s my wife!"',
		'And after all that, the goblin says to the lady "Wow, you sure you don\'t want me to eat him?"',
		'Then, just as the sun was beginning to rise, the mage looked over and saw it wasn\'t his spell book he\'d been protecting, it was a cookbook!',
		'So the ogre just took one look at him and says "I don\'t think that part should have spots..." so he let him go!',
		'But then, right as the kobold was going to leave the bar, the bartender says "wow, I guess that\'s what tipped...the scale!"',
		'and so she told me she wanted me to make a pact with her in exchange for eldritch power. I had to tell her I wasn\'t ready for that kind of commitment.',
		'Woman with a hook for a hand: "And that\'s why I\'ll never have tea with the baker\'s wife ever again!"',
		'Next thing I know, the bard has a broken lute string, the monk is ten feet in the air and the druid is stuck as a frog" (use this one when the party gets caught sneaking so they don\'t hear the end of the story).',
		'So if you just invest 50 copper and I invest 100 of my own, I know a guy who can turn that into 5 gold in two months.',
		'What would you know about pulling teeth? You\'re not a barber!',
		'And so I tells her "look, lady, the difference between your half-orc baby and a goblin teenager is pretty low, just be glad it was a flesh wound!"',
		'And at the end of the night, she realizes he had been using Mage Hand to seem bigger, he wasn\'t actually that big at all!',
		'So the adventurers ask the creed wizard "why?" And the wizard simply responded "I wanted to make egg salad..."',
		'then I said, "If you didn\'t want to turn to stone, you shouldn\'t have married Medusa!',
		'Then I said back to her "are you Medusa? Cuz I\'m hard as a rock!"',
		'so I sold him the bag of holding, but switched it at the last moment for the one filled with flumph farts!',
		'and that\'s how I got me hook leg and peg arm." as told by a pirate. ',
		'No, really!! He was just two halfling wrestlers in a trench coat! Honest!',
		'and then she screamed "Wait, that\'s not ale - that\'s camel piss!',
		'and that\'s how I found out that dwarf lasses have TWO beards!',
		'and so the Eunuch said, "That\'s not my sister.. that\'s my wife!"',
		'so the xorn says... wait, no, let me start again, it wasn\'t a xorn it was a half-orc. So this half-orc decides to join the army, wait what are you doing with that axe -',
		'and then Asmodeus says \"With fiends like these, who needs enemas?"',
		'"no, you see it\'s funny because the bard was fucking a mimic." "That\'s how all your jokes end." "Because it\'s always funny!"',
		'polishing her orbs with a cloaker!',
		'after I finished cleaning off the blood from the steps I was banned from entering any of her temples again. I still donate and spread the good word though',
		'and that\'s how I found out how to properly cook aboleth. It\'s quite nutritious',
		'and I tossed that dwarf good, if you know what I mean!',
		'That bard was here last night and I can\'t stop itching',
		'and that was the last time I ever hooked up with a beholder',
		'but then the rich dude takes one look at the dog, goes "mine isn\'t THAT shaggy", and shuts the door.',
		'and then I said, "That\'s no hag, that\'s my mother-in-law!"',
		'that\'s when I walked into the gelatinous cube!',
		'I don\'t care about the barmaid, is the cheese alright?!',
		'And then she screamed "they weren\'t Kobolds, they were children"',
		'and then he asked me, "Can you do anything other than eldritch blast?" and nobody\'s heard from him since...',
		'So the merrow says "those aren\'t oars, they\'re my sisters!"',
		'so the interrogator says, "What\'s with all the fish?" and I say, "I thought you said fillet!"',
		'good thing gnolls can\'t get rabies, right?"',
		'there was zero reason for you to joke about kidnapping the princess in front of the bard, you know.',
		'for the last time, nobody wants to hear about how you escaped the shapeshifter who was stalking you.',
		'really? You can do THAT to an orc?',
		'only a rookie adventurer would mistake a kobold for a lizardfolk. For one thing, they smell completely different!',
		'moreover, imagine what would have happened if I HADN\'T clocked the daylights out of that horse',
		'You know (guard / NPC name), I know you\'re all over this whole "natural" thing since you went spelunking with that druid girl, but as your pal? TAKE A BATH!',
		'and that\'s why I can never go back to (Location)!',
		'in short, NEVER do that while on top of a Minotaur. [shows missing eye]',
		'and right before I put him on bread and water, he says: "Please, I have a family!"',
		'nah, that was it, that\'s all he said really.',
	]
};