window.npcRace = {
	name: 'Races',
	items: [
        'Human',
        'Dwarf',
        'Elf',
        'Halfling',
        'Gnome',
        'Half-Elf',
        'Half-Orc',
        'Dragonborn',
        'Tiefling',
        'Aarakocra',
        'Genasi',
        'Goliath',
        'Aasimar',
        'Bugbear',
        'Firbolg',
        'Goblin',
        'Hobgoblin',
        'Kenku',
        'Kobold',
        'Lizardfolk',
        'Orc',
        'Tabaxi',
        'Triton',
        'Yuan-ti Pureblood',
        'Feral Tiefling',
        'Tortle',
        'Changeling',
        'Kalashtar',
        'Shifter',
        'Warforged',
        'Centaur',
        'Loxodon',
        'Minotaur',
        'Locathah',
        'Grung',
	]
};