window.badOmens = {
	name: 'Bad Omens',
	items: [
		'Cold spot',
		'Random dice roll behind screen (does nothing)',
		'Make perception check - does nothing (but have something minor in case they get 20)',
		'Total silence',
		'Metalic ozone smell in the air',
		'NPC complains of a splitting headache - 2 failed con saves (triggered every 5 mins real time) - skull bursts open and fight with 4-5 swarms of reskinned wasps',
		'Discover NPC weeping over the corpse of another NPC they have killed and now can\'t resist consuming',
		'Hear npc laughing/crying in an unhinged manner - discover npc methodically cutting off there own fingers 1 by 1 because they are "touched by evil" and believe they will do harm If they remain capable of using hands.',
		'hear NPC screaming which is rapidly cut short- discover the NPC tied up and hastily gagged with second npc who has cut off their face and placed it over the tied npc\'s. Injured npc continuously mutters "now I\'m you" before passing out. Heroes may save and restrain NPC. Besides PTSD tied npc is fine.',,
		'Everyone who fails a Con save on a poisoned air has bugs come out of their lungs',
		'NPC has slit their wrist. They are drawing runic symbols in their own blood all over their house. They can be stopped and possibly saved. If allowed to finish, the NPC dies of blood loss but the house becomes warded against (evil, supernatural, magic). Ward last until symbols are damaged or erased.',
		'NPC shepherd is found being eaten by (flock, herd) of (cows, goats, sheep). If disturbed possessed animals go on a rampage.',
		'An NPC is sitting at a table, their hair covers their face as they slump forward a bit. Their hand appears to be in their mouth and as we approach, they pull the last of their own teeth out and place them on the table in front of them.',
		'NPC is under the illusion that a beehive (or similar) is a hot nymph, and is fucking the hive and being stung. Eventualyl they will snap out of it',
		'A raven caws angrily at the party before flying away. More are seen periodically, perching and watching.',
		'A woman in the street drops an urn, which shatters. There\'s a moment of silence in the street.',
		'A baby won\'t stop crying in a nearby basket. If the players investigate, there is no child. The crying is gone.',
		'The campfire goes out in the middle of the night. There is no wind. It is difficult to restart as darkness closes in.',
		'The flames of nearby candles flicker out completely, but a moment later they return.',
		'The moon is larger and brighter than usual. It seems to dominate the sky, and cast harsh, pale shadows.',
		'A wooden road sign is snapped in half at a crossroads. It lies broken in the dirt.',
		'The clouds are gray and full of rain. And yet it does not rain. Though thunder rumbles, not a drop lands.',
		'A PC wakes up in the morning with a cut across their palm that wasn\'t there before.',
		'Animals go wild. Horses buck and have wide, scared eyes. Dogs bark fiercely and pull at their leashes.',
		'There\'s a large crack in a PC\'s drinking glass, and yet it doesn\'t break unless forced.',
		'A bird flies into the wall of a building and drops dead outside the door.',
		'A PC is contacted by the Sending spell, but they only hear heavy breathing and crying.',
		'The players hear distant, sourceless harp music. When pointed out or mentioned, it stops.',
		'An old man has a heart attack in the street. He stares directly at one of the PCs as he dies.',
		'A passed out drunk wakes suddenly and screams, clawing at his eyes. He runs and disappears.',
		'A strong wind that was blowing all day suddenly stops. The world is still for a few moments before life continues.',
		'A child chases an errant ball, only to trip and twist their ankle. The ball is not found.',
		'The temple doors are tossed open by a violent wind until a concerned acolyte rushes to close them.',
		'A black cat emerges from behind a corner, and passes through a PCs legs as if they were an archway, but they do not come out from the other end',
		'During a festival all of the buskers and musical acts stop at the same time and stare directly into the sun in silence. They never stop staring, although none can now see.',
		'An odd figure walking into a bar and going to the bathroom, bedroom, or similar isolated spot. If the players investigate, a totally normal person that looks nervous greets them instead. They have no memory of any odd figure.',
		'A frigid wind shrieks past you, tugging at your clothing and momentarily chilling you to the bone. The nearby flora are unaffected',
		'The background noise of birdcalls suddlenly stops. All the birds in view stop and look in one direction for a second or two, and then return to normal behavior',
		'Lightning smashes into a nearby tree out of a clear sky. Their ears ring and it smells like ozone. Inspecting the tree it was clear that the damage was done months ago',
	]
};