window.snSMission = [
	{mission: 'Attack', targetType: 'place'},
	{mission: 'Decipher', targetType: 'thing'},
	{mission: 'Destroy', targetType: 'thing'},
	{mission: 'Elude', targetType: 'person'},
	{mission: 'Escape', targetType: 'place'},
	{mission: 'Escort', targetType: 'person'},
	{mission: 'Explore', targetType: 'place'},
	{mission: 'Find', targetType: 'thing'},
	{mission: 'Guard', targetType: 'thing'},
	{mission: 'Kidnap', targetType: 'person'},
	{mission: 'Kill', targetType: 'person'},
	{mission: 'Locate', targetType: 'person'},
	{mission: 'Locate', targetType: 'thing'},
	{mission: 'Protect', targetType: 'person'},
	{mission: 'Question', targetType: 'person'},
	{mission: 'Recover', targetType: 'thing'},
	{mission: 'Rescue', targetType: 'person'},
	{mission: 'Seek', targetType: 'place'},
	{mission: 'Steal', targetType: 'thing'},
	{mission: 'Transport', targetType: 'thing'},
	{mission: 'Watch', targetType: 'place'},
];

window.snSPerson = [
	'Artist',
	'Assassin',
	'Beggar',
	'Craftsman',
	'Dancer',
	'Eunuch',
	'Foreigner',
	'Harlot',
	'Merchant',
	'Noble',
	'Noble',
	'Pirate',
	'Poet',
	'Priest',
	'Scholar',
	'Servant',
	'Slave',
	'Sorcerer',
	'Thief',
	'Warrior',
];

window.snSPlace = [
	'Abyss',
	'Bazaar',
	'Brothel',
	'Catacombs',
	'Cavern',
	'Fortress',
	'Garden',
	'Island',
	'Mansion',
	'Mountain',
	'Oasis',
	'Palace',
	'Pool',
	'Prison',
	'Sanctuary',
	'Shrine',
	'Storehouse',
	'Tomb',
	'Tower',
	'Valley',
];

window.snSThing = [
	'Bottle',
	'Chest',
	'Cloak',
	'Crown',
	'Crystal',
	'Dagger',
	'Helm',
	'Idol',
	'Jewel',
	'Lens',
	'Mask',
	'Meteorite',
	'Ring',
	'Sarcophagus',
	'Scroll',
	'Seal',
	'Skull',
	'Sword',
	'Tablet',
	'Tome',
];

window.snSHook = [
	'Ambushed and left for dead',
	'Arrested and pressed into service',
	'Asked as a favor',
	'Blackmailed',
	'Cursed by a god',
	'Dared or had courage questioned',
	'Found old map',
	'Geased by a sorcerer',
	'Had a dream or vision',
	'Heard a prophecy',
	'Heard a song or poem',
	'Hired',
	'Lost or shipwrecked',
	'Made a wager',
	'Ordered by superior',
	'Overheard conversation',
	'Read ancient scroll or tablet',
	'Repaying a debt',
	'Stumbled into situation',
	'Wronged and seeking revenge',
];

window.snSAntagonist = [
	'Angry ghost',
	'Bandit chieftain',
	'Brutal warlord',
	'Corrupt official',
	'Cult leader',
	'Cunning madman',
	'Debauched noble',
	'Demonized wretch',
	'Depraved monk',
	'Deranged alchemist',
	'Evil sorcerer',
	'Fanatical priest',
	'Greedy merchant',
	'King of thieves',
	'Obsessed scholar',
	'Pirate captain',
	'Ruthless slaver',
	'Sadistic torturer',
	'Sardonic harlequin',
	'Sinister revenant',
];

window.snSPotentialAlly = [
	'Aged warrior seeking one last battle',
	'Charismatic leader of a slave revolt',
	'Demon seeking the soul of antagonist',
	'Disgruntled servant of antagonist',
	'Escaped prisoner',
	'Friendly witch',
	'Honorable captain of the guard',
	'Local ruler whose throne was usurped',
	'Naïve and virtuous young warrior',
	'Priest who speaks for the gods',
	'Rival of antagonist',
	'Rogue adventurer seeking the same goal',
	'Strangely intelligent animal',
	'Streetwise urchin',
	'Sybil with an important prophecy',
	'Unworldly scholar with vital information',
	'Vengeful spirit',
	'Victim of antagonist seeking revenge',
	'Villain who wants to be redeemed',
	'Wise sage with useful lore',
];

window.snSComplication = [
	'Aspiring student or apprentice pesters a PC',
	'Astronomical alignment favors black magic',
	'Disguised sorcerer curses PC',
	'Eclipse or comet provokes outburst of superstitious fear',
	'Escaped slave boy or wench begs refuge',
	'Forgotten crime comes back to haunt a PC',
	'Important NPC under a spell',
	'Invasion or occupation by foreigners',
	'Local festival creates atmosphere of riot and license',
	'Local laws are bizarre and restrictive',
	'Locale suffering from recent earthquake or flood',
	'Money lender comes to collect from a PC',
	'Old rival of a PC becomes involved',
	'PC falsely accused of a capital crime',
	'PC mistaken for someone else',
	'Phobia or taboo of a PC is violated',
	'Plague is spreading in the vicinity',
	'Rebels are plotting to overthrow the government',
	'Spurned lover of a PC looks for revenge',
	'Unwanted suitor falls in love with a PC',
];

window.snSObstacle = [
	'Armed guards',
	'Assassins',
	'Bandits or pirates',
	'Concealment, deception, or secrecy',
	'Curse (real or imaginary)',
	'Deadly environment',
	'Dishonesty and greed of populace',
	'Great distance',
	'Inscription that needs translated',
	'Lack of supplies',
	'Limited time',
	'Looming natural or unnatural disaster',
	'Magical wards or guards',
	'Monster',
	'Native cannibals or headhunters',
	'Physical barrier',
	'Riddle that must be solved',
	'Roaming savage beasts',
	'Thieves',
	'Wrong or misleading information',
];

window.snSTwist = [
	'Adventure locale is a Potemkin village and supposed mission assigned to PCs is a sinister experiment',
	'Antagonist is a PC from another time or reality',
	'Antagonist is an ally or friend in disguise',
	'Antagonist is actually pursuing a worthy goal',
	'Antagonist is actually the puppet of another (roll on Antagonist table to determine actual Antagonist)',
	'Apparently mundane is actually supernatural',
	'Apparently supernatural is actually mundane',
	'Betrayal by supposed ally or friend',
	'Distortion of time or space in adventure locale',
	'Entire adventure is actually a delusion or dream',
	'Entire adventure is actually the jest of a mad god',
	'Forced to ally with enemy or rival',
	'Goals and motivations of important NPCs have been misrepresented',
	'Important NPC has a twin brother or sister, leading to mass confusion',
	'Original mission is actually a red herring (roll on Mission table to determine actual mission)',
	'Original mission is actually a trap and actual mission is to survive and escape',
	'Original mission is actually a wild goose chase, and new mission is revenge on perpetrator',
	'Portion of adventure is a wild goose chase',
	'Portion of adventure is actually a delusion or dream',
	'Success in mission leads to unexpected and dire consequences',
];

window.snSReward = [
	'Clue to another adventure',
	'Desirable lover',
	'Exotic spices or lotuses',
	'Favor of a cult or deity',
	'Favor of powerful NPC',
	'Gold',
	'Loyal henchman',
	'Magical armour, shield, or weapon',
	'Pardon for crimes',
	'Potion or alchemical preparation',
	'Precious jewels',
	'Rare and wondrous steed',
	'Rare furs or silks',
	'Scroll of spells, magic ring, magic wand, or other magic item',
	'Wench or manservant',
	'Nothing but their miserable hides',
];